# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tiny Contents
tagline:          'A Jekyll theme'
description:      'rippled through Rabinarayan Biswal's tiny experiences'
url:              'https://rabinarayanb.github.io'
baseurl:          /

author:
  name:           'Rabinarayan Biswal'
  url:            https://twitter.com/@biswalrabi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rabinarayanb/rabinarayanb.github.io
