# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Tiny Contents'
tagline:          'By Rabinarayan Biswal'
description:      'rippled through Rabinarayan Biswals tiny experiences'
url:              https://rabibiswal.github.io
baseurl:          /

author:
  name:           'Rabinarayan Biswal'
  url:            https://twitter.com/biswalrabi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
